# Generated by Django 2.0.2 on 2018-03-23 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInstance',
            fields=[
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('m', 'Maintenance'), ('o', 'On loan'), ('r', 'Reserved')], default='a', help_text='Key availability', max_length=1)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular key', primary_key=True, serialize=False)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roomkey'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('k', 'Kitchener'), ('h', 'Hamilton')], default='k', help_text='Office Location', max_length=1)),
                ('urgency', models.CharField(choices=[('2', 'Low'), ('1', 'Medium'), ('0', 'High')], default='l', help_text='Urgency of Request', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('s', 'Submitted'), ('w', 'Work in Progress'), ('c', 'Completed')], default='s', help_text='Request', max_length=1)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('request_comments', models.TextField(help_text='Enter a brief reason for request', max_length=250)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Request by')),
            ],
        ),
        migrations.CreateModel(
            name='RoomKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text='Enter the name of the room.', max_length=100)),
                ('room_des', models.CharField(help_text='Give a brief description of room (location)', max_length=200, verbose_name='Room description')),
            ],
        ),
        migrations.AddField(
            model_name='keyinstance',
            name='roomkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.RoomKey', verbose_name='Room'),
        ),
    ]
