# Generated by Django 2.0.2 on 2018-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='office',
            field=models.CharField(choices=[('k', 'Kitchener'), ('h', 'Hamilton')], default='k', max_length=1),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_comments',
            field=models.TextField(help_text='Enter a brief description of the request', max_length=250),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'Submitted'), ('w', 'Work in Progress'), ('c', 'Completed')], default='s', max_length=1),
        ),
    ]
