# Generated by Django 2.0.2 on 2018-04-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180406_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='roomkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.RoomKey', verbose_name='Key'),
        ),
    ]
