# Generated by Django 2.0.2 on 2018-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180406_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomkey',
            name='room_des',
            field=models.CharField(help_text='Give a brief description of the key', max_length=200, verbose_name='Key description'),
        ),
        migrations.AlterField(
            model_name='roomkey',
            name='room_name',
            field=models.CharField(help_text='Enter the name of the key.', max_length=100, verbose_name='Key name'),
        ),
    ]
