# Generated by Django 2.0.2 on 2018-04-06 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_auto_20180406_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinstance',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyinstance',
            name='request_status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Accepted'), ('d', 'Denied')], default='p', max_length=1, verbose_name='Request status'),
        ),
        migrations.AddField(
            model_name='keyinstance',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requested by'),
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='borrower',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Requested for'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Date to be returned'),
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Date approved'),
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved')], help_text='Key availability', max_length=1, verbose_name='Key status'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requested by'),
        ),
    ]
