# Generated by Django 2.0.2 on 2018-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180406_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='request_status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Accepted'), ('d', 'Denied')], default='p', max_length=1, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved')], help_text='Key availability', max_length=1, verbose_name='Key status'),
        ),
    ]
