# Generated by Django 2.0.2 on 2018-04-10 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0013_auto_20180406_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(help_text='Enter the full name of the person who will be responsible for the key', max_length=100)),
                ('request_status', models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Accepted'), ('d', 'Denied')], default='p', max_length=1, verbose_name='Request status')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('request_comments', models.TextField(help_text='Enter a brief reason for the request', max_length=2000)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
                ('roomkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.RoomKey', verbose_name='Key')),
            ],
        ),
        migrations.RemoveField(
            model_name='keyinstance',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='keyinstance',
            name='date_requested',
        ),
        migrations.RemoveField(
            model_name='keyinstance',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='keyinstance',
            name='requester',
        ),
        migrations.AddField(
            model_name='keyinstance',
            name='keyrequest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.KeyRequest', verbose_name='Key requests'),
        ),
    ]
