# Generated by Django 2.0.2 on 2018-04-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180410_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='roomkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.RoomKey', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='roomkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.RoomKey', verbose_name='Room'),
        ),
    ]
