# Generated by Django 2.0.2 on 2018-04-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180410_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='keyrequest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.KeyRequest', verbose_name='Key requests'),
        ),
    ]
