# Generated by Django 2.0.2 on 2018-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180410_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='request_status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied')], default='p', max_length=1, verbose_name='Request status'),
        ),
    ]
