# Generated by Django 2.0.2 on 2018-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20180411_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
