# Generated by Django 2.0.2 on 2018-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_keyrequest_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinstance',
            name='key_notes',
            field=models.CharField(blank=True, help_text='Key instance notes if applicable', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='roomkey',
            name='bitting_num',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the bitting number (max length 10)', null=True, verbose_name='Bitting #'),
        ),
        migrations.AddField(
            model_name='roomkey',
            name='key_symb',
            field=models.CharField(blank=True, help_text='Enter the keyset symbol', max_length=10, null=True, verbose_name='Keyset Symbol'),
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='roomkey',
            name='room_des',
            field=models.CharField(help_text='Give a brief description of the key', max_length=200, verbose_name='Room description'),
        ),
        migrations.AlterField(
            model_name='roomkey',
            name='room_name',
            field=models.CharField(help_text='Enter the name of the key.', max_length=100, verbose_name='Door #'),
        ),
    ]
