# Generated by Django 2.0.2 on 2018-04-19 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0019_auto_20180416_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_person', models.CharField(max_length=40)),
                ('move_to', models.CharField(max_length=100)),
                ('move_date', models.DateField(help_text='Enter the proposed date of move')),
                ('move_conditions', models.CharField(blank=True, max_length=2000, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
