# Generated by Django 2.0.4 on 2018-05-04 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0020_moverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.AddField(
            model_name='keyinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
