# Generated by Django 2.0.4 on 2018-05-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20180504_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set key as returned'),)},
        ),
    ]
