# Generated by Django 2.0.4 on 2018-05-15 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20180514_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='date_due_back',
            field=models.DateField(default=datetime.date(2018, 5, 29)),
        ),
    ]
