# Generated by Django 2.0.4 on 2018-05-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_keyrequest_date_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='keyrequest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='catalog.KeyRequest', verbose_name='Key requests'),
        ),
    ]
