# Generated by Django 2.0.4 on 2018-05-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20180515_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='keyrequest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.KeyRequest', verbose_name='Key requests'),
        ),
    ]
