# Generated by Django 2.0.4 on 2018-05-16 14:22

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20180515_1637'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='keyinstance',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='date_due_back',
            field=models.DateField(default=datetime.date(2018, 5, 30)),
        ),
    ]
