# Generated by Django 2.0.4 on 2018-05-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20180516_1022'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='keyinstance',
            managers=[
            ],
        ),
    ]
