# Generated by Django 2.0.4 on 2018-05-17 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20180516_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinstance',
            name='is_requested',
            field=models.BooleanField(default=False, help_text='Is this key being requested ?', verbose_name='Is requested'),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='date_due_back',
            field=models.DateField(default=datetime.date(2018, 5, 31)),
        ),
    ]
