# Generated by Django 2.0.4 on 2018-05-17 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20180516_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='date_due_back',
            field=models.DateField(default=datetime.date(2018, 5, 31)),
        ),
    ]
