# Generated by Django 2.0.4 on 2018-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20180517_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinstance',
            name='request_status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied')], default='p', max_length=1, verbose_name='Request status'),
        ),
    ]
