# Generated by Django 2.0.4 on 2018-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_keyinstance_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinstance',
            name='date_requested',
            field=models.DateField(blank=True, null=True),
        ),
    ]
