# Generated by Django 2.0.4 on 2018-05-18 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_keyinstance_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='borrower',
            field=models.CharField(default='testing', help_text='Enter the name of the borrower.', max_length=100, verbose_name='Borrower'),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='date_due_back',
            field=models.DateField(default=datetime.date(2018, 6, 1)),
        ),
    ]
