# Generated by Django 2.0.4 on 2018-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20180518_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='borrower',
            field=models.CharField(blank=True, help_text='Enter the name of the borrower.', max_length=100, null=True, verbose_name='Borrower'),
        ),
    ]
