# Generated by Django 2.0.4 on 2018-05-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20180518_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyinstance',
            name='keyrequest',
        ),
    ]
