# Generated by Django 2.0.4 on 2018-05-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20180522_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='date_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Date that it has been returned'),
        ),
    ]
