# Generated by Django 2.0.4 on 2018-06-04 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20180522_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinstance',
            name='borrower_email',
            field=models.CharField(blank=True, help_text='Enter the email address you would like to be notified on', max_length=100, null=True, verbose_name='Borrower Email'),
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Requested')], help_text='Key availability', max_length=1, verbose_name='Key status'),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='date_due_back',
            field=models.DateField(default=datetime.date(2018, 6, 18)),
        ),
    ]
